export { default as MainImg } from "./mainImg.png";
export { default as HeadLogo } from "./headLogo.svg";
export { default as SearchFont } from "./searchFont.svg";
export { default as ListImg } from "./listImg.svg";
export { default as ModalBackgroundImg } from "./modalBackground.svg";
export { default as Google } from "./google.svg";
export { default as Github } from "./github.svg";
export { default as Facebook } from "./facebook.svg";
export { default as SortArrow } from "./sortarrow.svg";
